### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by moboluwade** [moboluwade/dev-league#68]
You are tasked with developing a Responsive Navbar that provides admin users access to super functions such as adding new posts and blogs, and editing existing posts and blogs.
Using react-router to navigate to other views.

**Note**: Respond to this issue to get assigned

link to the figma:
https://www.figma.com/file/g24nINrCStaAf24FnQlGNC/DEV-LEAGUE?node-id=5549%3A911&mode=dev

<img width="132" alt="image" src="https://github.com/moboluwade/dev-league/assets/105948130/1a64074e-22cc-4f18-9dfe-a34d1f5c3b4d">

**Comment by Neverm1ndEZ** [comment]
Hey @moboluwade, can I work on this issue?

**Comment by moboluwade** [comment]
Sure @Neverm1ndEZ, give it a go.

**Comment by Neverm1ndEZ** [comment]
@moboluwade the Figma link is password-protected. So, kindly look into it
